# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Javascript CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Test command
      run: node ./bin/createNodeApp.js --folder node-js-project && cd node-js-project && npm run test && npm run prettier:check

    - name: Create Boilerplate Project
      run: node ./bin/createNodeApp.js --folder node-js-project

    - name: Open the Project
      run: cd node-js-project

    - name: Eslint check
      run: npm run eslint:check

    - name: Prettier check
      run: npm run prettier:check

    - name: Run Tests
      run: npm run test